### ISSUE TITLE
missing google.protobuf

### ISSUE THREAD

**Issue by Sir-Teabag** [OverStruck/deep-dream-maker#7]
Even after using this tutorial https://gist.github.com/sofyanhadia/37787e5ed098c97919b8c593f0ec44d8 I'm still getting the following error when I try to run the py script.

Any help is really really appreciated, i'm completely new to Python and i've been trying to get DeepDream to work for 2 solid days with no avail. 

https://pastebin.com/2MdTbDru 

Cheers!

**Comment by OverStruck** [comment]
Hello, I know this was posted in 2018, but please try the new docker version of the app. No more installing dependencies!
